# Generated by Django 3.2 on 2022-09-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=34)),
                ('lat_long', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
